#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1499198946 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
  # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Get Structured Today!

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Leo Mehlig
your_link: leomehlig.com
your_city: Berlin
email_address: leo@leomehlig.com
facebook_username:
instagram_username:
twitter_username: leoMehlig
github_username: leoMehlig
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Bring strucuture into your day
    description: Stop wasting time by splitting up your day into small tasks.
    fontawesome_icon_name: clock
  - title: A timeline of all todos and events
    description: A simple timeline of you day gives you the oversight to achieve your plans.
    fontawesome_icon_name: calendar-alt
  - title: Combines calendar and todo lists
    description: Plan you day and check of tasks and events once they where done.
    fontawesome_icon_name: check-circle
  - title: Reminders to keep you on track
    description: Enable reminders to never miss a task and always stay on track.
    fontawesome_icon_name: bell
  - title: AI-based icon recommendation for that extra touch
    description: Spark up your plan with some nice matching icons. The best one will automatically be recommended.
    fontawesome_icon_name: icons
  - title: Set start time and duration to get an exact overview
    description: By setting when a task will task and how long it will task, you will always know what to do next.
    fontawesome_icon_name: stopwatch
  - title: Automatic conflict resolution
    description: The app will automatically detect conflicts in your shedul and resolve them.
    fontawesome_icon_name: exclamation-circle

# Theme Settings
topbar_color: "#F4A099"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: # Replace with alternative image path or image URL.
cover_overlay_color: "#F4A099"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#F4A099"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#F4A099"
feature_icons_background_color: "#DEDEDE"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#DEDEDE"

footer_text_color: "#F4A099"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
